project:
  type: website

website:
  title: "TidyTuesday"
  description: "Homepage for Tidy Solutions on Python"
  favicon: /images/logo.jpeg

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd


  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Arun Koundinya Parasa"
    background: "#36494E" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



