---
title: "TidyTuesday Solved Soluitions"
subtitle: "By Arun Koundinya"
---

This website is designed to showcase my solutions to [TidyTuesday](https://github.com/rfordatascience/tidytuesday) challenges. In the initial weeks, I will focus on basic analysis and plotting. As the weeks progress, I aim to provide more sophisticated and holistic solutions.

The coding is done in python majorly using the following packages as of now:

-   pandas

-   numpy

-   plotnine { Similar to that of ggplot of R }

-   dfply { Similar to that of tidyverse of R }

May be in future may add matplotlib , plotly and shiny

| Tidy Tuesday Date | Dataset About                                                                                                              | Link for my approach                                     | Comments                 |
|------------------|-------------------|------------------|------------------|
| 16th Jan 2024     | [US Polling Places 2012-2020](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-01-16/readme.md)   | [Analysis-16012024](analysis/16012024/Tidy16012024.html) | My first Basic Line Plot |
| 30th Jan 2024     | [Groundhog predictions](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-01-30/readme.md)         | [Analysis-30012024](analysis/30012024/Tidy30012024.html) | Density Plots            |
| 13th Feb 2024     | [Valentine's Day consumer data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-02-13/readme.md) | [Analysis-13022024](analysis/13022024/Tidy13022024.html) | Column Plots             |